site_name: WEB II
site_url: https://jfinfocesde.github.io/25web2/
site_author: jhonfvg

theme:
  name: material
  language: es  
  icon:
    logo: octicons/code-16    
  features:    
    - navigation.tabs.sticky 
    - navigation.tabs
    - navigation.top
    # - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
  palette:    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode        

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra:
  generator: false  

copyright: 2025 &copy; by JFVG

nav:
  - Inicio: index.md  
  - Contenido:
      - content/p1.md
      - content/p2.md
      - content/p3.md
      - content/p4.md
      - content/p5.md
      # - content/p6.md
      # - content/p7.md
      # - content/p8.md 
      # - content/p9.md
      # - content/p10.md
      # - content/p11.md
      # - content/p12.md
      # - content/p13.md
      # - content/p14.md
      # - content/p15.md
      # - content/p16.md
      # - content/p17.md
      # - content/p18.md 


  # - Proyecto Integrador: 
  #     - pi/p1.md   
  - Typescript: 
      - course1/p1.md   
      - course1/p2.md   
      - course1/p3.md   
      - course1/p4.md   
      - course1/p5.md   
      - course1/p6.md   
      - course1/p7.md   
      - course1/p8.md   
      - course1/p9.md   
      - course1/p10.md   
      - course1/p11.md   
      - course1/p12.md   
  - Tailwind CSS: 
      - course2/p1.md   
      - course2/p2.md   
      - course2/p3.md   
      - course2/p4.md   
      - course2/p5.md   
      - course2/p6.md   
      - course2/p7.md   
      - course2/p8.md   
      - course2/p9.md   
      - course2/p10.md   
      - course2/p11.md   
  
  - Actvidades: 
      - activities/p1.md 
  - Tutoriales: 
      - tutorials/p1.md 

plugins:
  - search
  # - blog
  - glightbox


